// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scaicazwweklhnabsgtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjYWljYXp3d2VrbGhuYWJzZ3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODI2MTUsImV4cCI6MjA1ODY1ODYxNX0.v8WeYKOeD552oXQm08mhho2lMGbQo_EJWE36DBtTmgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);